apiVersion: apps/v1
kind: Deployment
metadata:
  name: naob-deployment
  labels:
    app: naob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naob
  template:
    metadata:
      labels:
        app: naob
    spec:
      containers:
      - name: naob
        image: gcr.io/norwegian-language-bank/naob:05d5dcd6-9d3f-46b7-9671-41d7ded84e8b
        command: [ "/bin/bash" ]
        args: [ "-c", "streamlit run naob-ordbok.py --server.port 8501 --server.baseUrlPath /naob --browser.gatherUsageStats=False"]
        ports:
        - containerPort: 8501
        resources:
          limits:
            cpu: 1
            ephemeral-storage: 256Mi
            memory: 1Gi
          requests:
            cpu: 1
            ephemeral-storage: 256Mi
            memory: 1Gi